doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: "%env(resolve:DOCTRINE_DB_DRIVER)%"
                server_version: "%env(resolve:DOCTRINE_DB_VERSION)%"
                path: "%env(resolve:DOCTRINE_DB_PATH)%"
                dbname: "%env(resolve:DOCTRINE_DB_NAME)%"
                host: "%env(resolve:DOCTRINE_DB_HOST)%"
                port: "%env(resolve:DOCTRINE_DB_PORT)%"
                user: "%env(resolve:DOCTRINE_DB_USER)%"
                password: "%env(resolve:DOCTRINE_DB_PASS)%"
            sqlite:
                driver: "%env(resolve:DOCTRINE_DB_DRIVER)%"
                server_version: "%env(resolve:DOCTRINE_DB_VERSION)%"
                path: "%env(resolve:DOCTRINE_DB_PATH)%"
                dbname: "%env(resolve:DOCTRINE_DB_NAME)%"
                host: "%env(resolve:DOCTRINE_DB_HOST)%"
                port: "%env(resolve:DOCTRINE_DB_PORT)%"
                user: "%env(resolve:DOCTRINE_DB_USER)%"
                password: "%env(resolve:DOCTRINE_DB_PASS)%"

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default # doctrine.dbal.connections.default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'Ixnode\PhpApiVersionBundle\Entity'
                        alias: App
            sqlite:
                connection: sqlite # doctrine.dbal.connections.sqlite
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'Ixnode\PhpApiVersionBundle\Entity'
                        alias: App

when@test:
    doctrine:
        dbal:
            connections:
                default:
                # "TEST_TOKEN" is typically set by ParaTest
                #dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
